#! /usr/bin/env python
import sys, os
def set_smart(list):
    actual = ""
    mutiple = 0
    out = [""]
    for x in list:
        if(actual == x and (not mutiple)): 
            out[-1] += "*"
            mutiple = 1
        if(actual != x): 
            out.append(x)
            mutiple = 0
        actual = x
    return out


file = (sys.argv[1])
if( len(sys.argv) == 3 ):
    element = (sys.argv[2])
    #os.system('echo "du //' + str(sys.argv[2]) + '/*" | xmllint --shell' + str(sys.agrv[1]))
    os.system('echo "du //' + element + '/*" | xmllint --shell ' + file)
if( len(sys.argv) == 2 ):
    set_ = (set(os.popen('echo "du /*" | xmllint --shell '  + file).read().replace(" ","").strip(">").strip("</").strip("/").split("\n")))
    print(" | ".join(list(set_)))
    print("")
    print("")
    print("")

    for element in set_:
        print("---------- ELEMENT :" + element + "-------------")
        try:
            l = os.popen('echo "du //' + element + '/*" | xmllint --shell ' + file).read().replace(" ","").strip(">").strip("</").strip("/").split("\n")
            print(" | ".join(list(set_smart(l))))
        except:
            print(" NODE ")

        print("")

            
